//! Issue #148 / AIVCS slice 3 — Human decision projection.
//!
//! Mirrors the `human_decision` table created in
//! `migrations/0017_aivcs_human_decision.sql`. The projection sits next to
//! the immutable `events_bronze` rows that record a human's decision —
//! the row's `resulting_event_id` points at that bronze record, while
//! the projection itself gives the UI a typed, indexed shape that can be
//! listed per run or per review without scanning the event log.
//!
//! Slice scope: types + storage shape only. HTTP routes
//! (`POST /api/aivcs/reviews/{id}/approve`, `request-changes`,
//! `guidance`, etc.) are deliberately left out of this slice.
//!
//! Cross-tenant safety (WS8): the storage layer binds `tenant_id` as the
//! leading parameter on every read and write; the SQL-shape tests in
//! `src/db.rs` pin that contract.
//!
//! Dead-code allows: the projection ships ahead of its consumers — the
//! HTTP routes (`POST /api/aivcs/reviews/{id}/approve`,
//! `request-changes`, `guidance`) land in the slice that follows. The
//! storage helpers exist now so the BFF/handler PR can compile against
//! them without re-introducing the migration. The crate-wide
//! `-D warnings` build needs each item allowed explicitly until those
//! callers land.

use std::str::FromStr;

use serde::{Deserialize, Serialize};

/// Typed variants of a human decision recorded against a run or review.
///
/// The string form is what gets stored in the `decision_type` column and
/// what the projection's by-type index keys on. Wire format (JSON) uses
/// the same snake_case form so the projection can be serialized straight
/// out to a BFF response.
#[allow(dead_code)]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "snake_case")]
pub enum HumanDecisionType {
    Approve,
    RequestChanges,
    Pause,
    Resume,
    Merge,
}

impl HumanDecisionType {
    /// Storage-layer string. Stable: schema, JSON wire format, and
    /// `decision_type` column all share this representation.
    #[allow(dead_code)]
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Approve => "approve",
            Self::RequestChanges => "request_changes",
            Self::Pause => "pause",
            Self::Resume => "resume",
            Self::Merge => "merge",
        }
    }
}

/// Error returned when [`HumanDecisionType::from_str`] sees a value that
/// is not one of the five known variants. Kept as a distinct type so
/// callers can match it directly without stringly-typed comparisons.
#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParseHumanDecisionTypeError {
    pub got: String,
}

impl std::fmt::Display for ParseHumanDecisionTypeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "unknown human_decision type {:?}; expected one of approve | request_changes | pause | resume | merge",
            self.got
        )
    }
}

impl std::error::Error for ParseHumanDecisionTypeError {}

impl FromStr for HumanDecisionType {
    type Err = ParseHumanDecisionTypeError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "approve" => Ok(Self::Approve),
            "request_changes" => Ok(Self::RequestChanges),
            "pause" => Ok(Self::Pause),
            "resume" => Ok(Self::Resume),
            "merge" => Ok(Self::Merge),
            other => Err(ParseHumanDecisionTypeError {
                got: other.to_string(),
            }),
        }
    }
}

/// Input shape for `create_human_decision`. `id` is generated by the
/// caller (the slice's HTTP handler, when it lands) so this struct does
/// not carry it — the caller mints a UUID, writes the bronze event, then
/// passes the bronze event id in `resulting_event_id`.
///
/// Optional fields:
/// * `run_id` / `review_id` — at least one is expected in practice (the
///   UI lists decisions by one or the other), but the storage layer does
///   not enforce that; a future slice can add a CHECK once the route
///   contract is settled.
/// * `policy_decision_id` — populated when a policy check ran before the
///   human decision (e.g. the approve gate required a policy allow).
/// * `resulting_event_id` — populated once the bronze event is written.
///   Left optional so the projection can be inserted in the same batch
///   as the event without a second update round-trip.
#[allow(dead_code)]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CreateHumanDecision {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub run_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub review_id: Option<String>,
    /// Actor recording the decision, e.g. `human:jane.taylor`. The
    /// `human:` prefix marks this as a human-sourced decision so the UI
    /// can distinguish from agent-sourced events without re-querying.
    pub actor: String,
    pub decision_type: HumanDecisionType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub policy_decision_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resulting_event_id: Option<String>,
}

/// Read shape for the `human_decision` projection. Mirrors the columns
/// of the table 1:1; `created_at` is populated by SQLite's
/// `datetime('now')` default and surfaced to the caller for ordering.
#[allow(dead_code)]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct HumanDecision {
    pub id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub run_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub review_id: Option<String>,
    pub actor: String,
    pub decision_type: HumanDecisionType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub policy_decision_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resulting_event_id: Option<String>,
    pub created_at: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every variant must round-trip through `as_str` / `FromStr` exactly
    /// — this is the contract the storage layer relies on when reading
    /// back the `decision_type` column.
    #[test]
    fn human_decision_type_round_trips_for_every_variant() {
        let all = [
            HumanDecisionType::Approve,
            HumanDecisionType::RequestChanges,
            HumanDecisionType::Pause,
            HumanDecisionType::Resume,
            HumanDecisionType::Merge,
        ];
        for variant in all {
            let s = variant.as_str();
            let parsed: HumanDecisionType = s
                .parse()
                .unwrap_or_else(|e| panic!("variant {variant:?} failed to round-trip: {e}"));
            assert_eq!(parsed, variant, "round-trip mismatch for {variant:?}");
        }
    }

    /// The wire format must use the same snake_case strings so the
    /// projection can be serialized straight to the BFF without a
    /// translation layer. This pins it against accidental rename.
    #[test]
    fn human_decision_type_serializes_as_snake_case_storage_string() {
        let cases = [
            (HumanDecisionType::Approve, "\"approve\""),
            (HumanDecisionType::RequestChanges, "\"request_changes\""),
            (HumanDecisionType::Pause, "\"pause\""),
            (HumanDecisionType::Resume, "\"resume\""),
            (HumanDecisionType::Merge, "\"merge\""),
        ];
        for (variant, expected_json) in cases {
            let json = serde_json::to_string(&variant).expect("serialize");
            assert_eq!(json, expected_json, "json shape for {variant:?}");
            let from_storage: HumanDecisionType =
                variant.as_str().parse().expect("storage round-trip");
            assert_eq!(from_storage, variant);
        }
    }

    #[test]
    fn human_decision_type_rejects_unknown_string() {
        let err = "approve_with_caveats"
            .parse::<HumanDecisionType>()
            .expect_err("unknown string must error");
        assert_eq!(err.got, "approve_with_caveats");
    }

    #[test]
    fn human_decision_struct_round_trips_through_json() {
        let original = HumanDecision {
            id: "hd-1".into(),
            run_id: Some("run-1".into()),
            review_id: Some("rev-1".into()),
            actor: "human:jane.taylor".into(),
            decision_type: HumanDecisionType::Approve,
            reason: Some("lgtm".into()),
            policy_decision_id: Some("pd-1".into()),
            resulting_event_id: Some("ev-1".into()),
            created_at: "2026-06-11T00:00:00.000Z".into(),
        };
        let json = serde_json::to_string(&original).expect("serialize");
        let parsed: HumanDecision = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(original, parsed);
    }

    #[test]
    fn create_human_decision_round_trips_through_json() {
        let original = CreateHumanDecision {
            run_id: None,
            review_id: Some("rev-1".into()),
            actor: "human:reviewer-7".into(),
            decision_type: HumanDecisionType::RequestChanges,
            reason: Some("please add tests".into()),
            policy_decision_id: None,
            resulting_event_id: None,
        };
        let json = serde_json::to_string(&original).expect("serialize");
        let parsed: CreateHumanDecision = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(original, parsed);
    }
}
